(self.AMP=self.AMP||[]).push({n:"amp-lightbox",ev:"0.1",l:true,v:"2104240357001",m:0,f:(function(AMP,_){
'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;
function r(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(q)q(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ra=b.prototype}var t;function u(a){return a?Array.prototype.slice.call(a):[]}function da(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function ea(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function v(){this.B=null}f=v.prototype;f.add=function(a){var b=this;this.B||(this.B=[]);this.B.push(a);return function(){b.remove(a)}};f.remove=function(a){this.B&&(a=this.B.indexOf(a),-1<a&&this.B.splice(a,1))};f.removeAll=function(){this.B&&(this.B.length=0)};f.fire=function(a){if(this.B)for(var b=this.B,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.B?this.B.length:0};function fa(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];if(e instanceof Error&&!b){b=void 0;var g=Object.getOwnPropertyDescriptor(e,"message");if(g&&g.writable)b=e;else{g=e.stack;var h=Error(e.message);for(b in e)h[b]=e[b];h.stack=g;b=h}}else c&&(c+=" "),c+=e}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function ha(a){var b=fa.apply(null,arguments);setTimeout(function(){self.__AMP_REPORT_ERROR&&self.__AMP_REPORT_ERROR(b);throw b;})};function ia(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ja=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var w="";
function ka(a){var b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b.location.originalHash||b.location.hash;var d=Object.create(null);if(c)for(var e;e=ja.exec(c);){var g=ia(e[1],e[1]);e=e[2]?ia(e[2].replace(/\+/g," "),e[2]):"";d[g]=e}w||(w=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012104240357001");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(d.development)||b.AMP_DEV_MODE),examiner:"2"==d.development,esm:!1,geoOverride:d["amp-geo"],minified:!0,test:!1,
log:d.log,version:"2104240357001",rtvVersion:w};c=b.__AMP_MODE=c}return c};var la=Object.prototype.hasOwnProperty;function x(a){return a||{}};function ma(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(h){for(var k=[],l=0;l<arguments.length;++l)k[l-0]=arguments[l];e=a.Date.now();g=k;d||(d=a.setTimeout(c,500))}};var y=self.AMP_CONFIG||{},na=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function oa(a){if(self.document&&self.document.head&&(!self.location||!na.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}y.cdnUrl||oa("runtime-host");y.geoApiUrl||oa("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function pa(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function A(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");};function B(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function E(a,b){var c=F(a);c=qa(c);return C(c,b)}function sa(a){a=F(a);a=qa(a);return ta(a,"action")?C(a,"action"):null}function F(a){return a.nodeType?B((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function qa(a){a=F(a);return a.isSingleDoc()?a.win:a}function C(a,b){ta(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function ta(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ua(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function va(a){return a.closest?a.closest(".i-amphtml-fie"):ua(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,".i-amphtml-fie"):!1})}function G(a){try{a.focus()}catch(b){}};function H(a){return E(a,"owners")};function I(a,b){var c=this;this.Aa=C(a,"timer");this.Ha=b;this.Ga=0;this.S=-1;this.fa=0;this.la=!1;this.Ca=function(){c.ba()}}I.prototype.isPending=function(){return-1!=this.S};I.prototype.schedule=function(a){var b=a||this.Ga;this.la&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.fa?(this.cancel(),this.fa=c,this.S=this.Aa.delay(this.Ca,b),!0):!1};I.prototype.ba=function(){this.S=-1;this.fa=0;this.la=!0;this.Ha();this.la=!1};
I.prototype.cancel=function(){this.isPending()&&(this.Aa.cancel(this.S),this.S=-1)};var J;function wa(a){if(void 0!==J)return J;J=!1;try{var b={get passive(){J=!0;return!1}};a.addEventListener("test-options",null,b);a.removeEventListener("test-options",null,b)}catch(c){}return J};function xa(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function ya(a,b,c){this.F=a;this.h=[];this.N=[];this.C=[];this.j=[];this.o=null;this.Oa=b;this.Pa=c;this.ca=!1;this.ba=new I(a.ownerDocument.defaultView,this.va.bind(this));this.xa=new v;this.R=Object.create(null);this.ta=this.Na.bind(this);this.ra=this.La.bind(this);this.sa=this.Ma.bind(this);this.qa=this.Ka.bind(this);var d=wa(a.ownerDocument.defaultView);this.F.addEventListener("touchstart",this.ta,d?{passive:!0}:!1);this.F.addEventListener("touchend",this.ra);this.F.addEventListener("touchmove",
this.sa,d?{passive:!0}:!1);this.F.addEventListener("touchcancel",this.qa);this.ha=!1}function za(a){var b=void 0===b?!1:b;var c=void 0===c?!1:c;var d=a.__AMP_Gestures;d||(d=new ya(a,b,c),a.__AMP_Gestures=d);return d}f=ya.prototype;f.cleanup=function(){this.F.removeEventListener("touchstart",this.ta);this.F.removeEventListener("touchend",this.ra);this.F.removeEventListener("touchmove",this.sa);this.F.removeEventListener("touchcancel",this.qa);delete this.F.__AMP_Gestures;this.ba.cancel()};
f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.R[d];e||(this.h.push(c),e=new v,this.R[d]=e);return e.add(b)};f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.R[b]){a.removeAll();a=da(this.h,function(c){return c.getType()==b});if(0>a)return!1;this.h.splice(a,1);this.C.splice(a,1);this.j.splice(a,1);this.N.splice(a,1);delete this.R[b];return!0}return!1};f.onPointerDown=function(a){return this.xa.add(a)};
f.Na=function(a){var b=Date.now();this.ca=!1;this.xa.fire(a);for(var c=0;c<this.h.length;c++)if(!this.C[c]&&(this.j[c]&&this.j[c]<b&&K(this,c),this.h[c].onTouchStart(a))){var d=c;this.N[d]=!0;this.j[d]=0}L(this,a)};f.Ma=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)this.N[c]&&(this.j[c]&&this.j[c]<b?K(this,c):this.h[c].onTouchMove(a)||K(this,c));L(this,a)};
f.La=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)if(this.N[c])if(this.j[c]&&this.j[c]<b)K(this,c);else{this.h[c].onTouchEnd(a);var d=!this.j[c],e=this.j[c]<b;this.o!=this.h[c]&&(d||e)&&K(this,c)}L(this,a)};f.Ka=function(a){for(var b=0;b<this.h.length;b++){var c=b;this.C[c]=0;K(this,c)}L(this,a)};
function L(a,b){var c=!!a.o||a.ca;a.ca=!1;if(!c)for(var d=Date.now(),e=0;e<a.h.length;e++)if(a.C[e]||a.j[e]&&a.j[e]>=d){c=!0;break}c?(b.stopPropagation(),a.Oa||b.preventDefault()):a.Pa&&b.stopPropagation();a.ha&&(a.ha=!1,a.va())}
f.va=function(){for(var a=Date.now(),b=-1,c=0;c<this.h.length;c++)if(!this.C[c])this.j[c]&&this.j[c]<a&&K(this,c);else if(-1==b||this.C[c]>this.C[b])b=c;if(-1!=b){var d=0;for(c=0;c<this.h.length;c++)!this.C[c]&&this.N[c]&&(d=Math.max(d,this.j[c]-a));if(2>d){a=b;c=this.h[a];for(var e=0;e<this.h.length;e++)if(e!=a){var g=e;this.C[g]=0;K(this,g)}this.C[a]=0;this.j[a]=0;this.o=c;c.acceptStart()}else this.ba.schedule(d)}};function K(a,b){a.N[b]=!1;a.j[b]=0;a.C[b]||a.h[b].acceptCancel()}
function M(a,b){this.Qa=a;this.aa=b}f=M.prototype;f.getType=function(){return this.Qa};f.signalReady=function(a){var b=this.aa;if(b.o)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.C[d]=c+a,b.j[d]=0);b.ha=!0}};f.signalPending=function(a){var b=this.aa;if(b.o)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.j[d]=c+a)};f.signalEnd=function(){var a=this.aa;a.o==this&&(a.o=null,a.ca=!0)};
f.signalEmit=function(a,b){var c=this.aa.R[this.getType()];c&&c.fire(new xa(this.getType(),a,Date.now(),b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function Aa(a,b,c){1>b&&(b=1);var d=.5+Math.min(b/33.34,.5);return a/b*d+c*(1-d)};function N(a,b,c,d){M.call(this,a,b);this.wa=c;this.Ba=d;this.o=!1;this.pa=this.oa=this.ia=this.$=this.za=this.ka=this.ja=this.K=this.J=this.M=this.L=0}r(N,M);f=N.prototype;f.onTouchStart=function(a){a=a.touches;return this.o&&a&&1<a.length?!0:a&&1==a.length?(this.za=Date.now(),this.L=a[0].clientX,this.M=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1<=b.length){var c=b[0];b=c.clientX;c=c.clientY;this.J=b;this.K=c;if(this.o)O(this,!1,!1,a);else if(a=Math.abs(b-this.L),b=Math.abs(c-this.M),this.wa&&this.Ba)(8<=a||8<=b)&&this.signalReady(-10);else if(this.wa)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.Ba)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};
f.onTouchEnd=function(a){var b=a.touches;b&&0==b.length&&this.o&&(this.o=!1,O(this,!1,!0,a),this.signalEnd())};f.acceptStart=function(){this.o=!0;this.ja=this.L;this.ka=this.M;this.ia=this.za;this.L=this.J;this.M=this.K;O(this,!0,!1,null)};f.acceptCancel=function(){this.o=!1};
function O(a,b,c,d){a.$=Date.now();var e=a.$-a.ia;if(!c&&4<e||c&&16<e){var g=Aa(a.J-a.ja,e,a.oa),h=Aa(a.K-a.ka,e,a.pa);if(!c||32<e||0!=g||0!=h)a.oa=1E-4<Math.abs(g)?g:0,a.pa=1E-4<Math.abs(h)?h:0;a.ja=a.J;a.ka=a.K;a.ia=a.$}a.signalEmit({first:b,last:c,time:a.$,deltaX:a.J-a.L,deltaY:a.K-a.M,startX:a.L,startY:a.M,lastX:a.J,lastY:a.K,velocityX:a.oa,velocityY:a.pa},d)}function Ba(a){N.call(this,"swipe-xy",a,!0,!0)}r(Ba,N);var P,Ca="Webkit webkit Moz moz ms O o".split(" "),Da={getPropertyPriority:function(){return""},getPropertyValue:function(){return""}};function Ea(a,b,c){if(b.startsWith("--"))return b;P||(P=Object.create(null));var d=P[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<Ca.length;g++){var h=Ca[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(P[b]=d)}return d}
function Fa(a,b){a=a.style;for(var c in b)a.setProperty(Ea(a,c),String(b[c]),"important")}function Q(a,b,c){(b=Ea(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function R(a,b){for(var c in b)Q(a,c,b[c])}function S(a){"display"in a&&A().error("STYLE","`display` style detected in styles. You must use toggle instead.");return a}function Ga(a){var b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")}
function Ha(a){for(var b=["transition"],c=0;c<b.length;c++)Q(a,b[c],null)};var T;x({c:!0,v:!0,a:!0,ad:!0});function Ia(a){return a.classList.contains("i-amphtml-fie")||!!va(a)};function Ja(a){return a.unmount()}function Ka(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)U(a[b],!1,!0,Ja);else U(a,!1,!0,Ja)}function U(a,b,c,d){if(b&&a.classList.contains("i-amphtml-element")&&(V(d,a),!c)){var e=a.getPlaceholder();e&&U(e,!0,!1,d);return}var g=a.getElementsByClassName("i-amphtml-element");a=null;for(b=0;b<g.length;b++){var h=g[b];if(c)V(d,h);else{a=a||[];for(var k=!1,l=0;l<a.length;l++)if(a[l].contains(h)){k=!0;break}k||(a.push(h),V(d,h))}}}
function V(a,b){try{a(b)}catch(c){ha(c)}};var La=['<i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad"><div>Ad</div><i-amphtml-ad-close-button class=amp-ad-close-button></i-amphtml-ad-close-button></i-amphtml-ad-close-header>'],X={"fade-in":{openStyle:x({opacity:1}),closedStyle:x({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:x({transform:"translate(0, 0)"}),closedStyle:x({transform:"translate(0, 100%)"}),durationSeconds:.2},"fly-in-top":{openStyle:x({transform:"translate(0, 0)"}),closedStyle:x({transform:"translate(0, -100%)"}),
durationSeconds:.2}};
function Y(a){var b=AMP.BaseElement.call(this,a)||this;b.na=null;b.D=null;b.P=b.win.document;b.T=null;b.ea=-1;b.U=!1;b.X=null;b.W=null;b.Z=null;b.Y=null;b.ga=null;b.I=!1;b.G=0;b.da=0;b.ma=null;b.V=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.A=null;b.H=null;b.O=null;var c=B(b.win,"platform");b.Ia=c.isIos();b.ua=ma(b.win,function(){var d=pa().assertElement(b.D,"E#19457 this.container_"),e=H(b.element);e.scheduleLayout(b.element,d);e.scheduleResume(b.element,d)});return b}r(Y,AMP.BaseElement);
f=Y.prototype;f.buildCallback=function(){var a=this;this.user().assert(la.call(X,this.V),"Invalid `animate-in` value %s",this.V);this.element.classList.add("i-amphtml-overlay");this.T=sa(this.element);Ma(this);this.registerDefaultAction(function(b){return Na(a,b.trust,b.caller)},"open");this.registerAction("close",function(b){return a.close(b.trust)});this.T.addToAllowlist("AMP-LIGHTBOX",["open","close"],["email"])};
function Oa(a){u(a.element.getElementsByClassName("i-amphtml-element")).forEach(function(b){H(a.element).setOwner(b,a.element)})}
function Pa(a){if(!a.D){var b=a.element;a.I=b.hasAttribute("scrollable");var c=a.getRealChildren();a.D=b.ownerDocument.createElement("div");a.I||a.applyFillContent(a.D);b.appendChild(a.D);c.forEach(function(d){a.D.appendChild(d)});a.I&&(Oa(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){Oa(a);Z(a,a.G)}),b.addEventListener("scroll",a.ya.bind(a)));if(!a.I)za(b).onGesture(Ba,function(){});Qa(a)}}
f.layoutCallback=function(){t||(t=Promise.resolve(void 0));var a=t;return a};function Na(a,b,c){if(!a.U){Pa(a);a.X=a.Fa.bind(a);a.P.documentElement.addEventListener("keydown",a.X);a.Z=a.Ja.bind(a);a.P.documentElement.addEventListener("focusin",a.Z);c&&(a.ga=c);var d=new ea,e=d.promise,g=d.resolve;a.getViewport().enterLightboxMode(a.element,e).then(function(){return Ra(a,g,b)})}}f.mutatedAttributesCallback=function(a){var b=a.open;void 0!==b&&(b?Na(this,2,document.activeElement):this.close(2))};
function Sa(a){var b=a.D.querySelector("[autofocus]");b&&G(b)}
function Ra(a,b,c){function d(){a.ua();b()}var e=a.element,g=X[a.V],h=g.durationSeconds,k=g.openStyle,l=g.closedStyle,D=Object.keys(k).map(function(W){return W+" "+h+"s ease-in"}).join(",");a.da++;a.I&&Q(e,"webkitOverflowScrolling","touch");Q(e,"transition",D);R(e,S(l));Ga(e);a.mutateElement(function(){e.scrollTop=0});Sa(a);a.mutateElement(function(){R(e,S(k))});g=a.D;a.I&&(a.ya(),Z(a,a.G));e.addEventListener("transitionend",d);e.addEventListener("animationend",d);a.setAsContainer();var ra=H(a.element);
ra.scheduleLayout(a.element,g);ra.scheduleResume(a.element,g);Ta(a,"lightboxOpen",c);E(a.getAmpDoc(),"history").push(function(){return a.close(c)}).then(function(W){a.ea=W});Ua(a);Va(a);Wa(a);a.U=!0}function Qa(a){var b=a.element;if(null!=b.getAttribute("close-button")){var c=b.ownerDocument||b;T&&T.ownerDocument===c||(T=c.createElement("div"));c=T;c.innerHTML=La[0];var d=c.firstElementChild;c.removeChild(d);a.A=d;b.insertBefore(a.A,a.D)}}
function Ua(a){if(a.A){a.W=a.Ea.bind(a);a.A.addEventListener("keydown",a.W);var b;a.measureMutateElement(function(){b=a.A.getBoundingClientRect().height},function(){a.A.classList.add("amp-ad-close-header");Fa(a.D,{"margin-top":b+"px","min-height":"calc(100vh - "+(b+"px)")})})}}function Wa(a){if(a.O||a.A)a.Y=a.Da.bind(a),a.H.addEventListener("click",a.Y)}function Xa(a){if(a.O||a.A)a.H.removeEventListener("click",a.Y),a.Y=null,a.A&&(a.A.removeEventListener("keydown",a.W),a.W=null)}f.Da=function(){this.close(3)};
f.Fa=function(a){"Escape"==a.key&&(a.preventDefault(),this.close(3))};f.Ea=function(a){"Enter"==a.key&&(a.preventDefault(),this.close(3))};f.close=function(a){var b=this;this.U&&(this.I&&Q(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){return Ya(b,a)}))};
function Ya(a,b){function c(){e==a.da&&(a.collapse(),a.ua())}var d=a.element,e=++a.da;Za(a)?(Ha(d),c()):(d.addEventListener("transitionend",c),d.addEventListener("animationend",c));R(d,S(X[a.V].closedStyle));-1!=a.ea&&E(a.getAmpDoc(),"history").pop(a.ea);a.P.documentElement.removeEventListener("keydown",a.X);a.X=null;a.P.documentElement.removeEventListener("focusin",a.Z);a.Z=null;Xa(a);a.removeAsContainer();Ka(a.element);H(a.element).schedulePause(a.element,a.D);a.U=!1;Ta(a,"lightboxClose",b);a.ga&&
G(a.ga)}function Za(a){return"inabox"==ka(a.win).runtime||Ia(a.element)}f.Ja=function(){this.element.contains(document.activeElement)||this.close(3)};
function Va(a){if(!a.element.contains(document.activeElement)){a:if(a.H)var b=a.H;else if(a.A)b=a.A;else{b=a.element;for(var c=b.querySelectorAll("[on]"),d=0;d<c.length;d++){var e=c[d];if(a.T.hasResolvableActionForTarget(e,"tap",b,e.parentElement)){b=e;break a}}b=void 0}a.H=b;a.H||(b=a.element.getAttribute("data-close-button-aria-label")||"Close the modal",c=a.P.createElement("button"),c.textContent=b,c.classList.add("i-amphtml-screen-reader"),c.tabIndex=-1,a.O=c,a.element.insertBefore(a.O,a.element.firstChild),
a.H=a.O);G(a.H)}}f.ya=function(){var a=this.element.scrollTop;this.Ia&&(0==a?this.element.scrollTop=1:this.element.scrollHeight==a+this.element.offsetHeight&&(this.element.scrollTop=a-1));this.G=a;null===this.ma&&$a(this,a)};
function $a(a,b){a.ma=C(a.win,"timer").delay(function(){if(30>Math.abs(b-a.G)){A().fine("amp-lightbox","slow scrolling: %s - %s",b,a.G);a.ma=null;var c=a.G;A().fine("amp-lightbox","update_");Z(a,c);a.G=c}else A().fine("amp-lightbox","fast scrolling: %s - %s",b,a.G),$a(a,a.G)},100)}function Z(a,b){var c=[];ab(a,b,function(d){c.push(d);H(a.element).scheduleLayout(a.element,d)})}
function ab(a,b,c){a.na||(a.na={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.na.height,e=u(a.element.getElementsByClassName("i-amphtml-element")),g=0;g<e.length;g++){for(var h=e[g],k=0,l=h;l&&a.element.contains(l);l=l.offsetParent)k+=l.offsetTop;var D=2*d;k+h.offsetHeight>=b-D&&k<=b+D&&c(h)}}function Ma(a){var b=a.win;Ia(a.element)&&bb(b,b.document.body)}
function Ta(a,b,c){var d=a.win;var e="amp-lightbox."+b;var g=x({}),h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?e=new d.CustomEvent(e,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(e,!!h.bubbles,!!h.cancelable,g),e=d);a.T.trigger(a.element,b,e,c)}
function bb(a,b){var c={},d=B(a,"ampdoc").getAmpDoc(b);E(d,"mutator").measureMutateElement(b,function(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||Da)["background-color"]},function(){c.alreadyTransparent||pa().warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.");Fa(b,{background:"transparent"})})}
(function(a){"inabox"==ka().runtime&&bb(window,document.body);a.registerElement("amp-lightbox",Y,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}i-amphtml-ad-close-header{height:60px!important;display:block!important;visibility:visible!important;opacity:0;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:1000!important;display:-ms-flexbox!important;display:flex!important;-ms-flex-align:center!important;align-items:center!important;-ms-flex-pack:right!important;justify-content:right!important;transition:opacity 0.1s ease-in}[animate-in=fly-in-bottom]>i-amphtml-ad-close-header,[animate-in=fly-in-top]>i-amphtml-ad-close-header{transition-delay:0.2s}.amp-ad-close-header{opacity:1!important;box-sizing:border-box;padding:5px;line-height:40px;background-color:#000;color:#fff;font-family:Helvetica,sans-serif;font-size:12px;cursor:pointer}.amp-ad-close-header>:first-child{margin-left:auto!important;pointer-events:none!important}.amp-ad-close-button{display:block!important;background:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='%23fff'%3E%3Cpath d='M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E\") no-repeat;background-position:50%;width:40px;height:40px;pointer-events:none!important;border-radius:40px;margin-left:5px}.amp-ad-close-header:active>.amp-ad-close-button{background-color:hsla(0,0%,100%,0.3)}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-lightbox-0.1.js.map
